### ISSUE TITLE
[🐛] builderbot@latest - Error al recibir un mensaje nuevo e intentar guardar el contact con Postgresql

### ISSUE THREAD

**Issue by rodrimarchese** [codigoencasa/bot-whatsapp#1030]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Base de datos

### Describe tu problema

Pasos que hice:

1-Cree nuevo proyecto utilizando `pnpm create builderbot@latest` [baileys, postgres, typescript]
2-Introduje mi .env con mis credenciales de mi DB de Postgres (NO toque nada del codigo que viene por defecto)
3-Conecte mi wpp
4-Recibi un "Hola"
5-Error a continuacion:

```
Error registering history entry: error: null value in column "phone" of relation "contact" violates not-null constraint
    at /Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/pg@8.11.4/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.save (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+database-postgres@1.1.0/node_modules/@builderbot/database-postgres/dist/index.cjs:1:856)
    at async CoreClass.sendProviderAndSave (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:14350:17)
    at async Object.promiseInFunc (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:14052:25)
    at async Queue.processItem (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:726:27)
    at async Promise.all (index 0)
    at async Queue.processQueue (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:807:13) {
  length: 499,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (2, null, 2024-04-02 17:59:50.5162, null, null, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "INSERT INTO contact (phone)\n' +
    '                VALUES (in_phone)\n' +
    '                RETURNING id"\n' +
    'PL/pgSQL function save_or_update_history_and_contact(character varying,character varying,text,text,character varying,jsonb) line 8 at SQL statement',
  schema: 'public',
  table: 'contact',
  column: 'phone',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1968',
  routine: 'ExecConstraints'
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

error: null value in column "phone" of relation "contact" violates not-null constraint
    at /Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/pg@8.11.4/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.save (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+database-postgres@1.1.0/node_modules/@builderbot/database-postgres/dist/index.cjs:1:856)
    at async CoreClass.sendProviderAndSave (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:14350:17)
    at async Object.promiseInFunc (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:14052:25)
    at async Queue.processItem (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:726:27)
    at async Promise.all (index 0)
    at async Queue.processQueue (/Users/rodrimarchese/LTMsoluciones/base-ts-baileys-postgres/node_modules/.pnpm/@builderbot+bot@1.1.0/node_modules/@builderbot/bot/dist/index.cjs:807:13) {
  length: 499,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (2, null, 2024-04-02 17:59:50.5162, null, null, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "INSERT INTO contact (phone)\n' +
    '                VALUES (in_phone)\n' +
    '                RETURNING id"\n' +
    'PL/pgSQL function save_or_update_history_and_contact(character varying,character varying,text,text,character varying,jsonb) line 8 at SQL statement',
  schema: 'public',
  table: 'contact',
  column: 'phone',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1968',
  routine: 'ExecConstraints'
}

Node.js v21.7.1
Failed running './src/app.ts'
```

Asumo que el problema viene de que por alguna razon "phone" me queda en null, ya sea por un tiempo (o no), y que la db no lo acepta.

**Comment by rodrimarchese** [comment]
<img width="1208" alt="image" src="https://github.com/codigoencasa/bot-whatsapp/assets/32769860/98bb133b-42c0-4525-9b56-52bcd0db2bfd">

Me gustaria ayudar, pero quizas este NOT NULL esta por algo, no se si la solucion sera sacarlo u otra cosa.

**Comment by Elimeleth** [comment]
> <img alt="image" width="1208" src="https://private-user-images.githubusercontent.com/32769860/318953238-98bb133b-42c0-4525-9b56-52bcd0db2bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjIwMDMsIm5iZiI6MTcxMjE2MTcwMywicGF0aCI6Ii8zMjc2OTg2MC8zMTg5NTMyMzgtOThiYjEzM2ItNDJjMC00NTI1LTliNTYtNTJiY2QwZGIyYmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE2MjgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNmRhMzk2ZWIzYmYzODg4MjRmOWIxNDM0Y2NlMzU2ZGY2ZTNlNmYwNzk1MzdhM2E0NjQyNTIzOGYwYTlmMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dUbmkZWUya0Hh_3_yXEtHrCGgtoXxqyQgbXy8MdKroY">
> 
> Me gustaria ayudar, pero quizas este NOT NULL esta por algo, no se si la solucion sera sacarlo u otra cosa.

Al crearse por primera vez se dispara una funcion plpsql la cual crea un history mockup, espera un phone el cual no esta representado aún en la interfaz, se anexa el from el cual ya es conocido

**Comment by rodrimarchese** [comment]
@Elimeleth perdona, algo entendi, pero no me quedo claro si fue una sugerencia para un fix. Si necesitas estoy dispuesto a ayudarte a fixearlo, pero deberias decir que es lo que hay que cambiar

**Comment by Elimeleth** [comment]
> @Elimeleth perdona, algo entendi, pero no me quedo claro si fue una sugerencia para un fix. Si necesitas estoy dispuesto a ayudarte a fixearlo, pero deberias decirme que es lo que hay que cambiar

ya esta hecho :) 

https://github.com/codigoencasa/bot-whatsapp/pull/1031

**Comment by rodrimarchese** [comment]
> > @Elimeleth perdona, algo entendi, pero no me quedo claro si fue una sugerencia para un fix. Si necesitas estoy dispuesto a ayudarte a fixearlo, pero deberias decirme que es lo que hay que cambiar
> 
> ya esta hecho :)
> 
> #1031

No lo habia visto. Muchas gracias!!
