### ISSUE TITLE
INVALID_ARGUMENT: Input text not set[🐛]

### ISSUE THREAD

**Issue by christanov** [codigoencasa/bot-whatsapp#1069]
### ¿Que versión estas usando?

v1

### ¿Sobre que afecta?

DialogFlow

### Describe tu problema

En una instalación basada en Docker de base-bailey-postgres@1.0.0 tengo de forma esporádica el siguiente log de error:
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: 3 INVALID_ARGUMENT: Input text not set.
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at /app/node_modules/@google-cloud/dialogflow/build/src/v2/sessions_client.js:242:29
    at /app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/app/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /app/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCallPromise.call (/app/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/app/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /app/node_modules/google-gax/build/src/createApiCall.js:84:30 {
  code: 3,
  details: 'Input text not set.',
  metadata: Metadata {
    internalRepr: Map(3) {
      'endpoint-load-metrics-bin' => [
        Buffer(27) [Uint8Array] [
           49, 176,  5, 134, 181,  75, 243,  77,
            7,  64, 73,  53,  38, 183, 121, 169,
           64,  57, 34,  34,  66, 203,  36, 195,
          124, 193, 63

]
      ],
      'grpc-server-stats-bin' => [
        Buffer(10) [Uint8Array] [
          0, 0, 71, 117, 132,
          2, 0,  0,   0,   0
       
]
      ],
      'pc-high-bwd-bin' => [ Buffer(6) [Uint8Array] [ 75, 103, 73, 89, 74, 65 ] ]
    },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}

**Comment by ozzyoss77** [comment]
@christanov la versión que estas usando es muy antigua, te sugiero pasar a Builderbot para que pruebes si lo que experimentas ya esta solucionado.

`pnpm create builderbot@latest`

Tambien puedes pasarte por nuestro canal de Discord para soporte adicional.
https://discord.com/channels/915193197645402142/970206231849492480
