### ISSUE TITLE
[🐛] Error and disconect 

### ISSUE THREAD

**Issue by loja5combr** [codigoencasa/bot-whatsapp#1074]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Otro

### Describe tu problema

AxiosError: connect EPIPE 157.240.12.53:443
    at AxiosError.from (/root/base-baileys-json/node_modules/axios/dist/node/axios.cjs:841:14)
    at RedirectableRequest.handleRequestError (/root/base-baileys-json/node_modules/axios/dist/node/axios.cjs:3106:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/root/base-baileys-json/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/root/base-baileys-json/node_modules/axios/dist/node/axios.cjs:4224:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getHttpStream (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:320:21)
    at async downloadEncryptedContent (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:453:21)
    at async downloadExternalBlob (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:254:20)
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:233:26
    at async Promise.all (index 0)
    at async extractSyncdPatches (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:220:5)
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:384:33
    at async Object.transaction (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26) {
  port: 443,
  address: '157.240.12.53',
  syscall: 'connect',
  code: 'EPIPE',
  errno: -32,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      Origin: 'https://web.whatsapp.com',
      'User-Agent': 'axios/1.7.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    responseType: 'stream',
    method: 'get',
    url: 'https://mmg.whatsapp.net/v/t62.31695-24/11967450_834083668653559_3838815886823202593_n.enc?ccb=11-4&oh=01_Q5AaIExSSGBhfrMQAF9WwPpqKcmcU8c4DZg_3SOdS2SlhCTq&oe=66A96738&_nc_sid=e6ed6c',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/v/t62.31695-24/11967450_834083668653559_3838815886823202593_n.enc?ccb=11-4&oh=01_Q5AaIExSSGBhfrMQAF9WwPpqKcmcU8c4DZg_3SOdS2SlhCTq&oe=66A96738&_nc_sid=e6ed6c',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'mmg.whatsapp.net',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/v/t62.31695-24/11967450_834083668653559_3838815886823202593_n.enc',
      search: '?ccb=11-4&oh=01_Q5AaIExSSGBhfrMQAF9WwPpqKcmcU8c4DZg_3SOdS2SlhCTq&oe=66A96738&_nc_sid=e6ed6c'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /v/t62.31695-24/11967450_834083668653559_3838815886823202593_n.enc?ccb=11-4&oh=01_Q5AaIExSSGBhfrMQAF9WwPpqKcmcU8c4DZg_3SOdS2SlhCTq&oe=66A96738&_nc_sid=e6ed6c HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Origin: https://web.whatsapp.com\r\n' +
        'User-Agent: axios/1.7.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: mmg.whatsapp.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v/t62.31695-24/11967450_834083668653559_3838815886823202593_n.enc?ccb=11-4&oh=01_Q5AaIExSSGBhfrMQAF9WwPpqKcmcU8c4DZg_3SOdS2SlhCTq&oe=66A96738&_nc_sid=e6ed6c',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'mmg.whatsapp.net',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://mmg.whatsapp.net/v/t62.31695-24/11967450_834083668653559_3838815886823202593_n.enc?ccb=11-4&oh=01_Q5AaIExSSGBhfrMQAF9WwPpqKcmcU8c4DZg_3SOdS2SlhCTq&oe=66A96738&_nc_sid=e6ed6c',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect EPIPE 157.240.12.53:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -32,
    code: 'EPIPE',
    syscall: 'connect',
    address: '157.240.12.53',
    port: 443
  }
}
Error: Connection Closed
    at sendRawMessage (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:59:19)
    at sendNode (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:78:16)
    at query (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:142:15)
    at /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:368:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transaction (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:334:9
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/event-buffer.js:105:36
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:552:17
    at async Object.transaction (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
Error: Connection Closed
    at sendRawMessage (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:59:19)
    at sendNode (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:78:16)
    at query (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:142:15)
    at /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:368:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transaction (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:334:9
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/event-buffer.js:105:36
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:552:17
    at async Object.transaction (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
Error: Connection Closed
    at sendRawMessage (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:59:19)
    at sendNode (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:78:16)
    at query (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:142:15)
    at /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:368:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transaction (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:334:9
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/event-buffer.js:105:36
    at async /root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:552:17
    at async Object.transaction (/root/base-baileys-json/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by ozzyoss77** [comment]
Necesitas proporcionar mas información describiendo el problema, aca solo se puede observar que hubo un error en axios.

**Comment by leifermendez** [comment]
Prueba actualizando a builderbot te dejo link https://www.builderbot.app/en/tutorials/migrate-to-builderbot
