### ISSUE TITLE
falla al escanear luego de Escanear QR

### ISSUE THREAD

**Issue by danielruiz1094** [codigoencasa/bot-whatsapp#120]
C:\Users\soporte-jr\Desktop\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:19:123
    at ExecutionContext._evaluateInternal (C:\Users\soporte-jr\Desktop\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\soporte-jr\Desktop\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\Users\soporte-jr\Desktop\bot-whatsapp\node_modules\whatsapp-web.js\src\Client.js:267:9)

Node.js v19.0.0

**Comment by KH-APKSTUDIO** [comment]
pudiste resolver el error

**Comment by danielruiz1094** [comment]
Para resolverlo hice lo siguiente:

Despues de instalados los modulos con *npm install* en la siguiente ruta node_modules\whatsapp-web.js\src\util en el archivo Injected.js en la linea 22

window.Store.GroupMetadata = window.mR.findModule((module) => module.default && module.default.handlePendingInvite)[0].default;

se reemplazo por lo siguiente

window.Store.GroupMetadata = window.mR.findModule('GroupMetadata')[0].default.GroupMetadata;

**Comment by Aronchavez** [comment]
Ver QR http://localhost:3000/qr
C:\Users\Chavez\ARON SAMIR\NETBOB\CHATBOT(WHATSAPP)\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isMDBackend')
    at __puppeteer_evaluation_script__:13:68
    at ExecutionContext._evaluateInternal (C:\Users\Chavez\ARON SAMIR\NETBOB\CHATBOT(WHATSAPP)\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Chavez\ARON SAMIR\NETBOB\CHATBOT(WHATSAPP)\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\Users\Chavez\ARON SAMIR\NETBOB\CHATBOT(WHATSAPP)\bot-whatsapp-main\node_modules\whatsapp-web.js\src\Client.js:267:9)

Node.js v18.12.1


Presento el mismo error y puse lo de arriba pero no me funciona

**Comment by danielruiz1094** [comment]
Borra la carpeta de auth, ejecutas con los cambios y no te debe de salir el error

**Comment by Aronchavez** [comment]
@danielruiz1094 pudiste implementar los botones?

**Comment by Jonathan-Mendoza** [comment]
> Borra la carpeta de auth, ejecutas con los cambios y no te debe de salir el error

Me ayudas a identificar esa carpeta por favor

**Comment by IJustDavi** [comment]
![image](https://user-images.githubusercontent.com/87678581/205982847-443bd9e6-65f6-4e6f-94d8-a8114e3cd22b.png)
carpeta .wwebjs_auth, aparece oculta.

**Comment by KJoaquin** [comment]
Para botones tienes que actualizar el repo

npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list

Y el error que no te corre el programa es por que tienes que hacer el update

npm update 

o directamente al whatsapp

npm install whatsapp-web.js@1.18.4

**Comment by cheveguerra** [comment]
!Estos errores ya están corregidos en la **versión 2** del bot!!

**Comment by cheveguerra** [comment]
!Estos errores ya están corregidos en la **versión 2** del bot!!  👍🏽

[Ver la documentación](https://bot-whatsapp.netlify.app/docs/migration/)
