### ISSUE TITLE
Error in library puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221

### ISSUE THREAD

**Issue by basher2** [codigoencasa/bot-whatsapp#52]
I get this error message when receiving a message:

            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));

rror: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'features')
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:92:39)
    at __puppeteer_evaluation_script__:10:45
    at ExecutionContext._evaluateInternal (/home/bot/bot-whatsapp-main/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/bot/bot-whatsapp-main/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.sendMessage (/home/bot/bot-whatsapp-main/node_modules/whatsapp-web.js/src/Client.js:594:28)

**Comment by Gonzalito87** [comment]
actualizar a la V1.16.6 de whatsapp-web.js y este inconveniente se fixea

**Comment by leifermendez** [comment]
@Gonzalito87 si gustas envíame un PR solo con el cambio de versión

**Comment by MarioJarrinV** [comment]
Hola estoy con el mismo error me podrían explicar como solucionarlo porfavor.

throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isMDBackend')
    at __puppeteer_evaluation_script__:13:68
    at ExecutionContext._evaluateInternal (F:\chatbot\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (F:\chatbot\bot-whatsapp-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (F:\chatbot\bot-whatsapp-main\node_modules\whatsapp-web.js\src\Client.js:221:9)
