### ISSUE TITLE
Can't add new command when connection is in closed state[🐛]

### ISSUE THREAD

**Issue by spg-unsm** [codigoencasa/bot-whatsapp#783]
### ¿Que versión estas usando?

v2

### ¿Sobre que afecta?

Flujo de palabras (Flow)

### Describe tu problema

Hola leifermendez tengo un problema al desplegar el bot en ubunto con pm2 me sale el siple error:

Error: Can't add new command when connection is in closed state
    at Connection._addCommandClosedState (/home/unsm/base-baileys-mysql/node_modules/mysql2/lib/connection.js:148:17)
    at Connection.query (/home/unsm/base-baileys-mysql/node_modules/mysql2/lib/connection.js:546:17)
    at /home/unsm/base-baileys-mysql/node_modules/@bot-whatsapp/database/lib/mysql/index.cjs:39:21
    at new Promise (<anonymous>)
    at MyslAdapter.getPrevByNumber (/home/unsm/base-baileys-mysql/node_modules/@bot-whatsapp/database/lib/mysql/index.cjs:37:9)
    at CoreClass.handleMsg (/home/unsm/base-baileys-mysql/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:616:48)
    at BaileysProvider.func (/home/unsm/base-baileys-mysql/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:594:33)
    at BaileysProvider.emit (node:events:513:28)
    at EventEmitter.func (/home/unsm/base-baileys-mysql/node_modules/@bot-whatsapp/provider/lib/baileys/index.cjs:409:22)
    at EventEmitter.emit (node:events:513:28) {
  fatal: true
}
como podría solucionarlo

**Comment by Fabiobonato07** [comment]
El error que estás viendo parece sugerir que estás intentando ejecutar una consulta en una conexión MySQL que ya ha sido cerrada.

Aquí hay un par de cosas que podrías intentar:

1. **Verificar la conexión a la base de datos**: Asegúrate de que estás abriendo la conexión a la base de datos antes de intentar ejecutar cualquier consulta. Además, no deberías cerrar la conexión hasta que hayas terminado de ejecutar todas las consultas que necesitas.

2. **Manejar la desconexión de la base de datos**: Puede ser que la conexión a la base de datos se esté cerrando inesperadamente. Para manejar esto, podrías establecer un controlador de eventos para el evento `disconnect` en la conexión a la base de datos y volver a conectarte a la base de datos cuando esto ocurra.

3. **Verificar el manejo de errores**: Asegúrate de que estás manejando correctamente los errores que pueden ocurrir al ejecutar consultas a la base de datos. Esto podría implicar volver a intentar la consulta si falla, o mostrar un mensaje de error al usuario.

Si estos pasos no ayudan a resolver el problema, necesitaría más detalles sobre cómo estás abriendo y cerrando la conexión a la base de datos, y cómo estás ejecutando las consultas a la base de datos. También sería útil ver el código que estás usando para hacer esto.
