### ISSUE TITLE
node:events:495

### ISSUE THREAD

**Issue by WitchHunter777** [codigoencasa/bot-whatsapp#975]
npm start

> base-bailey-memory@1.0.0 prestart
> npx eslint . --no-ignore

> base-bailey-memory@1.0.0 start
> node app.js

node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1811:16)
    at listenInCluster (node:net:1859:12)
    at Server.listen (node:net:1947:7)
    at Polka.listen (/root/base-baileys-memory/node_modules/polka/index.js:66:22)
    at start (/root/base-baileys-memory/node_modules/@bot-whatsapp/portal/lib/portal.http.cjs:65:10)
    at main (/root/base-baileys-memory/app.js:76:5)
    at Object.<anonymous> (/root/base-baileys-memory/app.js:79:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1838:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v18.19.0

**Comment by WitchHunter777** [comment]
ya se elimino el archivo y volvio a iniciar reinstalando todo, actualizando y demas. :/

**Comment by ozzyoss77** [comment]
@WitchHunter777 el error te dice que el puerto 3000 donde trata de levantarse el proyecto esta en uso, te ercomiendo que revises que aplicación, proyecto o código esta corriendo en el puerto 3000.

Si estas usando linux puedes correr este comando:

`
lsof -i :3000
`
Procedes a matar el proceso que esta ocupando el puerto e inicializas el bot.
Otra opción es que cambies el puerto donde se ejecuta el bot:

`
QRPortalWeb(port: 3001);
`
